// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHWwy3uCty6Xs3PjRh5KMez1oEekB7jmU',
    appId: '1:934873983222:web:980b0e367958ffdaf864d7',
    messagingSenderId: '934873983222',
    projectId: 'flutter-week-6',
    authDomain: 'flutter-week-6.firebaseapp.com',
    storageBucket: 'flutter-week-6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcKW2jc3PNPNC3TzxcvMJh_dsL3FVMP8',
    appId: '1:934873983222:android:67497d3a2740fab6f864d7',
    messagingSenderId: '934873983222',
    projectId: 'flutter-week-6',
    storageBucket: 'flutter-week-6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGdO05HINUEPi-ZcI3c3_RTyLt1mfRYE',
    appId: '1:934873983222:ios:a3c4e8d2f9a19c09f864d7',
    messagingSenderId: '934873983222',
    projectId: 'flutter-week-6',
    storageBucket: 'flutter-week-6.appspot.com',
    androidClientId: '934873983222-66u862p6kea2d73d26ttcqdks21vkppd.apps.googleusercontent.com',
    iosClientId: '934873983222-incr1dgkbbufktdm4h8r9s7vs7t3rp8p.apps.googleusercontent.com',
    iosBundleId: 'com.4st.app.stdioWeek6',
  );
}
